-- Migration for chat message persistence following Vercel AI SDK pattern
-- This modifies our existing schema to work with useChat hook

-- Drop the existing messages table and recreate with the correct structure
DROP TABLE IF EXISTS messages;

-- Create messages table compatible with Vercel AI SDK useChat format
CREATE TABLE messages (
  id text PRIMARY KEY,                    -- message ID (generated by AI SDK)
  conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content text NOT NULL,
  audio_url text,                         -- MP3 in generated-audio bucket for assistant messages
  created_at timestamptz DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- RLS Policy - users can only access messages for their conversations
CREATE POLICY "Users can only access messages for their conversations"
  ON messages FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM conversations
      JOIN persons ON persons.id = conversations.person_id
      WHERE conversations.id = messages.conversation_id
      AND persons.user_id = auth.uid()
    )
  );

-- Add index for performance
CREATE INDEX idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX idx_messages_created_at ON messages(created_at);